from typing import cast

from pydantic import BaseModel, Field

from src.common.types import (
    AgentOutputArtifactPayload,
    ArtifactReferencePayload,
    JSONObject,
)


class ArtifactReference(BaseModel):
    """
    L3 冷數據指針 (Cold Data Pointer)

    Points to large artifacts stored in the Artifact Store.
    Frontend can fetch these asynchronously via the download_url.
    """

    artifact_id: str = Field(..., description="UUID of the artifact in the store")
    download_url: str = Field(
        ...,
        description="API endpoint to fetch the artifact (e.g., /api/artifacts/{id})",
    )
    type: str = Field(
        ...,
        description="Artifact type identifier (e.g., 'financial_report', 'news_analysis')",
    )


class AgentOutputArtifact(BaseModel):
    """
    Standard container for all Sub-Agent outputs.

    This structure implements a three-tier data architecture:
    - L1 (summary): Message bubble text (<500 chars) - Always present
    - L2 (preview): Hot data for immediate UI rendering (<1KB) - Optional
    - L3 (reference): Cold data pointer for async loading - Optional

    This ensures efficient state management by avoiding large data duplication
    in LangGraph checkpoints.
    """

    # L1: Message bubble text
    summary: str = Field(
        ..., description="L1: Short summary for message bubble (<500 chars)"
    )

    # L2: Preview (熱數據) - UI 立即渲染用
    preview: dict[str, object] | None = Field(
        default=None,
        description="L2: Hot data for immediate UI rendering (<1KB). Generated by Mapper from State.",
    )

    # L3: Reference (冷數據) - UI 異步加載用
    reference: ArtifactReference | None = Field(
        default=None,
        description="L3: Cold data pointer for async loading. Points to Artifact Store.",
    )


def to_artifact_reference_payload(
    reference: ArtifactReference,
) -> ArtifactReferencePayload:
    return cast(ArtifactReferencePayload, reference.model_dump(mode="json"))


def to_artifact_payload(artifact: AgentOutputArtifact) -> AgentOutputArtifactPayload:
    return cast(AgentOutputArtifactPayload, artifact.model_dump(mode="json"))


def build_artifact_payload(
    summary: str,
    preview: JSONObject | None,
    reference: ArtifactReference | None,
) -> AgentOutputArtifactPayload:
    artifact = AgentOutputArtifact(
        summary=summary, preview=preview, reference=reference
    )
    return to_artifact_payload(artifact)
