from __future__ import annotations

from dataclasses import dataclass

from src.agents.technical.interface.contracts import AnalystPerspectiveModel

INTERPRETATION_GUARDRAIL_VERSION = "ta_interpretation_guardrail_v2"

_BULLISH_HINTS = (
    "bullish",
    "uptrend",
    "upward",
    "breakout",
    "strengthening",
    "strong buy",
    "buy",
    "long",
)
_BEARISH_HINTS = (
    "bearish",
    "downtrend",
    "downward",
    "breakdown",
    "weakening",
    "strong sell",
    "sell",
    "short",
)
_NEUTRAL_HINTS = (
    "neutral",
    "sideways",
    "range",
    "range-bound",
    "consolidation",
    "choppy",
    "indecision",
    "flat",
    "hold",
    "wait",
)


@dataclass(frozen=True)
class InterpretationGuardrailOutcome:
    perspective: AnalystPerspectiveModel
    is_aligned: bool
    detected_direction: str | None
    violation_reason: str | None
    guardrail_version: str = INTERPRETATION_GUARDRAIL_VERSION


def apply_interpretation_guardrail(
    *,
    direction: str,
    risk_level: str,
    perspective: AnalystPerspectiveModel,
) -> InterpretationGuardrailOutcome:
    expected = _normalize_expected_direction(direction)
    perspective = _sanitize_perspective(perspective)
    normalized_summary = perspective.rationale_summary.strip()
    if not normalized_summary:
        fallback = _fallback_perspective(expected, risk_level)
        return InterpretationGuardrailOutcome(
            perspective=fallback,
            is_aligned=False,
            detected_direction=None,
            violation_reason="interpretation_empty",
        )

    detected = _detect_direction_hint(perspective.stance)
    if detected is None:
        return InterpretationGuardrailOutcome(
            perspective=perspective,
            is_aligned=True,
            detected_direction=None,
            violation_reason=None,
        )

    if detected != expected:
        fallback = _fallback_perspective(expected, risk_level)
        return InterpretationGuardrailOutcome(
            perspective=fallback,
            is_aligned=False,
            detected_direction=detected,
            violation_reason=f"direction_mismatch:expected={expected},detected={detected}",
        )

    return InterpretationGuardrailOutcome(
        perspective=perspective,
        is_aligned=True,
        detected_direction=detected,
        violation_reason=None,
    )


def _normalize_expected_direction(direction: str) -> str:
    upper = (direction or "").upper()
    if "BULLISH" in upper:
        return "bullish"
    if "BEARISH" in upper:
        return "bearish"
    return "neutral"


def _detect_direction_hint(text: str) -> str | None:
    lowered = text.lower()
    bullish_hits = _count_hits(lowered, _BULLISH_HINTS)
    bearish_hits = _count_hits(lowered, _BEARISH_HINTS)
    neutral_hits = _count_hits(lowered, _NEUTRAL_HINTS)

    scores = {
        "bullish": bullish_hits,
        "bearish": bearish_hits,
        "neutral": neutral_hits,
    }

    max_hits = max(scores.values())
    if max_hits == 0:
        return None
    top = [label for label, count in scores.items() if count == max_hits]
    if len(top) != 1:
        return None
    return top[0]


def _count_hits(text: str, hints: tuple[str, ...]) -> int:
    return sum(1 for hint in hints if hint in text)


def _fallback_perspective(expected: str, risk_level: str) -> AnalystPerspectiveModel:
    if expected == "bullish":
        stance = "BULLISH_WATCH"
    elif expected == "bearish":
        stance = "BEARISH_WATCH"
    else:
        stance = "NEUTRAL"
    return AnalystPerspectiveModel(
        stance=stance,
        stance_summary=f"{stance.replace('_', ' ').title()} with {risk_level} risk.",
        rationale_summary=(
            "Technical analysis indicates a "
            f"{stance.replace('_', ' ').lower()} posture with {risk_level} risk. "
            "This interpretation is aligned with the deterministic signal."
        ),
        plain_language_summary=(
            "The technical picture stays aligned with the deterministic signal, "
            "but this fallback view should be treated as a simplified summary."
        ),
        top_evidence=[],
        trigger_condition=None,
        invalidation_condition=None,
        invalidation_level=None,
        validation_note="Generated by deterministic guardrail fallback.",
        confidence_note=None,
        decision_posture="WAIT" if stance == "NEUTRAL" else "CONFIRMATION_NEEDED",
    )


def _sanitize_perspective(
    perspective: AnalystPerspectiveModel,
) -> AnalystPerspectiveModel:
    plain_language_summary = perspective.plain_language_summary
    if isinstance(plain_language_summary, str):
        plain_language_summary = plain_language_summary.strip() or None
    if plain_language_summary is None:
        plain_language_summary = perspective.rationale_summary.strip()
    signal_explainers = (
        perspective.signal_explainers[:3] if perspective.signal_explainers else None
    )
    top_evidence = perspective.top_evidence[:3] if perspective.top_evidence else None
    return perspective.model_copy(
        update={
            "plain_language_summary": plain_language_summary,
            "signal_explainers": signal_explainers,
            "top_evidence": top_evidence,
        }
    )


__all__ = [
    "InterpretationGuardrailOutcome",
    "apply_interpretation_guardrail",
    "INTERPRETATION_GUARDRAIL_VERSION",
]
