from __future__ import annotations

from .model_selection_contracts import ModelSpec
from .valuation_model import ValuationModel

MODEL_SPECS: tuple[ModelSpec, ...] = (
    ModelSpec(
        model=ValuationModel.DDM,
        label="Dividend Discount Model",
        description="Best for regulated, dividend-centric businesses (banks/utilities).",
        sector_keywords=("financial", "bank", "utilities", "utility"),
        industry_keywords=("bank", "banking", "regional bank", "utility"),
        sic_ranges=((6000, 6999),),
        required_fields=("net_income", "total_equity"),
        requires_profitability=True,
        base_score=3.0,
    ),
    ModelSpec(
        model=ValuationModel.FFO,
        label="FFO (REIT)",
        description="Adjusts for non-cash depreciation in real estate companies.",
        sector_keywords=("real estate",),
        industry_keywords=("reit", "real estate"),
        sic_ranges=((6798, 6798),),
        required_fields=("net_income", "extension_ffo"),
        requires_profitability=None,
        base_score=3.0,
    ),
    ModelSpec(
        model=ValuationModel.DCF_GROWTH,
        label="DCF (Growth)",
        description="Growth-adjusted DCF for high-growth tech or reinvestment-heavy firms.",
        sector_keywords=(
            "technology",
            "information technology",
            "communication services",
        ),
        industry_keywords=("software", "saas", "internet", "semiconductor", "cloud"),
        sic_ranges=(),
        required_fields=(
            "total_revenue",
            "operating_cash_flow",
            "net_income",
        ),
        requires_profitability=None,
        prefers_high_growth=True,
        base_score=2.0,
    ),
    ModelSpec(
        model=ValuationModel.DCF_STANDARD,
        label="DCF (Standard)",
        description="Stable cash flow businesses with predictable economics.",
        sector_keywords=("industrial", "material", "energy", "consumer", "health care"),
        industry_keywords=("manufacturing", "consumer", "pharma", "energy"),
        sic_ranges=(),
        required_fields=(
            "total_revenue",
            "operating_cash_flow",
            "net_income",
        ),
        requires_profitability=True,
        base_score=1.5,
    ),
    ModelSpec(
        model=ValuationModel.EV_REVENUE,
        label="EV/Revenue",
        description="Pre-profit companies with strong top-line growth.",
        sector_keywords=("technology", "communication services"),
        industry_keywords=("software", "saas", "internet", "biotech"),
        sic_ranges=(),
        required_fields=("total_revenue",),
        requires_profitability=False,
        prefers_preprofit=True,
        prefers_high_growth=True,
        base_score=1.0,
    ),
    ModelSpec(
        model=ValuationModel.EV_EBITDA,
        label="EV/EBITDA",
        description="Comparables-based valuation for positive EBITDA businesses.",
        sector_keywords=(),
        industry_keywords=(),
        sic_ranges=(),
        required_fields=("total_revenue", "net_income"),
        requires_profitability=True,
        base_score=0.5,
    ),
    ModelSpec(
        model=ValuationModel.RESIDUAL_INCOME,
        label="Residual Income",
        description="Equity valuation based on excess returns over required return.",
        sector_keywords=("financial", "bank", "insurance"),
        industry_keywords=("bank", "insurance", "financial"),
        sic_ranges=((6000, 6999),),
        required_fields=("net_income", "total_equity"),
        requires_profitability=True,
        base_score=0.3,
    ),
    ModelSpec(
        model=ValuationModel.EVA,
        label="EVA",
        description="Firm valuation based on economic value added.",
        sector_keywords=(),
        industry_keywords=(),
        sic_ranges=(),
        required_fields=("net_income", "total_assets"),
        requires_profitability=True,
        base_score=0.2,
    ),
)
