from __future__ import annotations

from ..extractor import SearchType
from ..mapping import (
    CF_STATEMENT_TOKENS,
    IS_STATEMENT_TOKENS,
    USD_UNITS,
    FieldSpec,
    XbrlMappingRegistry,
)


def register_base_income_fields(registry: XbrlMappingRegistry) -> None:
    registry.register(
        "total_revenue",
        FieldSpec(
            name="Total Revenue",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:Revenues",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:SalesRevenueNet",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:RevenuesNetOfInterestExpense",
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:InterestRevenueExpense",
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "operating_income",
        FieldSpec(
            name="Operating Income (EBIT)",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:OperatingIncomeLoss",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:OperatingIncomeLossContinuingOperations",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "income_before_tax",
        FieldSpec(
            name="Income Before Tax",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxes",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:IncomeBeforeTax",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:PretaxIncome",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "interest_expense",
        FieldSpec(
            name="Interest Expense",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:InterestExpense",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:InterestExpenseDebt",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                # US-GAAP 2024+ often reports operating/non-operating interest split.
                SearchType.CONSOLIDATED(
                    "us-gaap:InterestExpenseOperating",
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:InterestExpenseNonoperating",
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:FinanceLeaseInterestExpense",
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "depreciation_and_amortization",
        FieldSpec(
            name="Depreciation & Amortization",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationAndAmortization",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationAndAmortization",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationDepletionAndAmortization",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationDepletionAndAmortization",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationAmortizationAndAccretionNet",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:DepreciationAmortizationAndAccretionNet",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "DepreciationAmortizationAndOther",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:Depreciation",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:Depreciation",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "share_based_compensation",
        FieldSpec(
            name="Share-Based Compensation",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensation",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensation",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensationExpense",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensationExpense",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensationCost",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
                SearchType.CONSOLIDATED(
                    "us-gaap:ShareBasedCompensationCost",
                    statement_types=CF_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "net_income",
        FieldSpec(
            name="Net Income",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:NetIncomeLoss",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )

    registry.register(
        "income_tax_expense",
        FieldSpec(
            name="Income Tax Expense",
            configs=[
                SearchType.CONSOLIDATED(
                    "us-gaap:IncomeTaxExpenseBenefit",
                    statement_types=IS_STATEMENT_TOKENS,
                    period_type="duration",
                    unit_whitelist=USD_UNITS,
                ),
            ],
        ),
    )
