from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

DEFAULT_MIN_USABLE_ROWS = 20
DEFAULT_MIN_ANCHOR_COVERAGE = 0.6


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate forward signal calibration pipeline report gates.",
    )
    parser.add_argument(
        "--path",
        type=Path,
        required=True,
        help="Pipeline report JSON path generated by calibration pipeline runner.",
    )
    parser.add_argument(
        "--min-usable-rows",
        type=int,
        default=_env_int(
            "FUNDAMENTAL_CALIBRATION_MIN_USABLE_ROWS",
            DEFAULT_MIN_USABLE_ROWS,
        ),
        help="Minimum required usable_row_count.",
    )
    parser.add_argument(
        "--min-anchor-coverage",
        type=float,
        default=_env_float(
            "FUNDAMENTAL_CALIBRATION_MIN_ANCHOR_COVERAGE",
            DEFAULT_MIN_ANCHOR_COVERAGE,
        ),
        help="Minimum required anchor coverage (resolved_count / row_count).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = _read_report(args.path)

    row_count = _coerce_int(payload.get("row_count"))
    usable_row_count = _coerce_int(payload.get("usable_row_count"))
    anchor_stats_raw = payload.get("anchor_stats")
    resolved_count = None
    if isinstance(anchor_stats_raw, dict):
        resolved_count = _coerce_int(anchor_stats_raw.get("resolved_count"))

    issues: list[str] = []
    if row_count is None or row_count < 1:
        issues.append("row_count_missing_or_invalid")
    if usable_row_count is None:
        issues.append("usable_row_count_missing_or_invalid")
    if resolved_count is None:
        issues.append("anchor_resolved_count_missing_or_invalid")

    anchor_coverage = None
    if (
        row_count is not None
        and row_count > 0
        and usable_row_count is not None
        and resolved_count is not None
    ):
        if usable_row_count < max(int(args.min_usable_rows), 0):
            issues.append(
                "usable_row_count_below_threshold:"
                f"{usable_row_count}<{int(args.min_usable_rows)}"
            )
        anchor_coverage = resolved_count / float(row_count)
        if anchor_coverage < float(args.min_anchor_coverage):
            issues.append(
                "anchor_coverage_below_threshold:"
                f"{anchor_coverage:.4f}<{float(args.min_anchor_coverage):.4f}"
            )

    output = {
        "path": str(args.path),
        "row_count": row_count,
        "usable_row_count": usable_row_count,
        "anchor_resolved_count": resolved_count,
        "anchor_coverage": anchor_coverage,
        "min_usable_rows": int(args.min_usable_rows),
        "min_anchor_coverage": float(args.min_anchor_coverage),
        "gate_passed": len(issues) == 0,
        "issues": issues,
    }
    print(json.dumps(output, ensure_ascii=False))
    if issues:
        return 1
    return 0


def _read_report(path: Path) -> dict[str, object]:
    raw = path.read_text(encoding="utf-8")
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        raise TypeError("pipeline report root must be an object")
    return dict(parsed)


def _coerce_int(raw: object) -> int | None:
    if raw is None or isinstance(raw, bool):
        return None
    if isinstance(raw, int):
        return raw
    if isinstance(raw, float):
        if raw != raw:
            return None
        return int(raw)
    if isinstance(raw, str):
        normalized = raw.strip()
        if not normalized:
            return None
        try:
            return int(float(normalized))
        except ValueError:
            return None
    return None


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(float(raw))
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


if __name__ == "__main__":
    raise SystemExit(main())
